name: Build and Publish nameapp

on:
  pull_request:
    paths:
      - 'Dockerfile'

jobs:
  build_and_push_nameapp:
    name: Build and Push image to Docker Hub
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: aksy121/actionapp:latest
